FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    python3-pygame \
    libgl1-mesa-glx libegl1 libopengl0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

CMD ["python", "flappy.py"]